spring:
  application.name: lab2

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password


  liquibase:
    enabled: true
    change-log: classpath:liquibase/liquibase.xml

logging:
  level:
    root: DEBUG

debug: true